### ISSUE TITLE
`second_node` argument in `defineDabomColNms()`

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/DABOM#35]
In `defineDabomColNms()`, I added a new argument `second_node =` which allows the users to define the `bottom_sites` using the node_order column from `PITcleaner::buildNodeOrder()`. This was a method used by RK. Adding `second_node =` allowed me to eliminate a number of "duplicate" functions i.e., those I added with a _LGR suffix.

The change is in commit 4414b5b9fafa26c74cfee3efabe67f0d3e2f0d15

However, I don't know if a) this is the best way to do this, or b) is something useful for other `root_site`s. Could use a review from @KevinSee

**Comment by KevinSee** [comment]
I'm intrigued by this, because it might make the `defineDABOMColNms` function a lot more generic. Currently there are lots of hard-coded pieces in here to help organize the columns in a capture history matrix. That organization might be more for the user than the actual model though. 

I'll want to test it on some other DABOM models in the Upper Columbia. Some of them have a tributary and another mainstem dam as the first branch, so it may not work exactly the same. Wondering if we could do something with RKM instead, like pick out the bottom sites as those with RKMs that differ in a fundamental way from the root site. 

And maybe have a very generic option that doesn't require any information, just the parent child table and builds something based on the node order (which might be what the `second_node == TRUE` option does now).

**Comment by KevinSee** [comment]
In the `npt_develop` branch, I made the `second_node = TRUE` option the default for all `root_sites`. That does make it a much more generic function, able to accommodate any set of sites starting anywhere, not just one of the 4 previous options. I kept those options however if `second_node == FALSE`, because they do organize the detection histories in a more coherent way for anyone looking in detail at the actual 1's and 0's.
